table Dim_Departamento
	lineageTag: 14ae2f86-ecf8-42e4-a88a-268b60d7250d

	column departamento
		dataType: string
		lineageTag: c778041d-86c2-4e2a-97e7-c35894c7c650
		summarizeBy: none
		sourceColumn: departamento

		annotation SummarizationSetBy = Automatic

	column id_departamento
		dataType: int64
		formatString: 0
		lineageTag: 4a609b69-5a9d-40a2-a513-44090fce8de2
		summarizeBy: none
		sourceColumn: id_departamento

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_Departamento = m
		mode: import
		source =
				let
				  Origen = Excel.Workbook(File.Contents(RutaMaterial & "nike_data.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Departamentos", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"DEPARTMENT", type text}, {"id_DEPARTMENT", Int64.Type}}, "es"),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Tipo de columna cambiado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Filas en blanco eliminadas",{{"DEPARTMENT", "departamento"}, {"id_DEPARTMENT", "id_departamento"}}),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas con nombre cambiado",{"id_departamento", "departamento"})
				in
				  #"Columnas reordenadas"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

