table Dim_Sucursal_Estado
	lineageTag: 06450c83-e8f8-4a60-94cb-6a93c02889d5

	column id_estado
		dataType: int64
		formatString: 0
		lineageTag: bc95b3d0-2fe4-4e1c-a52d-5216c3ab2c77
		summarizeBy: none
		sourceColumn: id_estado

		annotation SummarizationSetBy = Automatic

	column sucursales
		dataType: string
		lineageTag: f935bf50-21b3-4ec2-8669-f5fdebd5f73c
		summarizeBy: none
		sourceColumn: sucursales

		annotation SummarizationSetBy = Automatic

	partition Dim_Sucursal_Estado = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents(RutaMaterial & "Sucursales_Estados.csv"), [Delimiter = ";", Columns = 2, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"id_State", Int64.Type}, {"Sucursales", type text}}, "es"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo de columna cambiado",{{"id_State", "id_estado"}, {"Sucursales", "sucursales"}})
				in
				  #"Columnas con nombre cambiado"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

