table Dim_Categoria
	lineageTag: c1429b90-93aa-4fc6-b473-8ee1a737e17b

	column categoria
		dataType: string
		lineageTag: 8cd8531e-d45e-4e28-8eb7-21bd56cf37a5
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column id_categoria
		dataType: int64
		formatString: 0
		lineageTag: 45e514a7-6c41-49c3-b961-b7989f0912ea
		summarizeBy: none
		sourceColumn: id_categoria

		annotation SummarizationSetBy = Automatic

	partition Dim_Categoria = m
		mode: import
		source =
				let
				  Origen = Excel.Workbook(File.Contents(RutaMaterial & "nike_data.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Categorías", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"CATEGORY", type text}, {"id_Category", Int64.Type}}, "es"),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Tipo de columna cambiado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Filas en blanco eliminadas",{"id_Category", "CATEGORY"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"id_Category", "id_categoria"}, {"CATEGORY", "categoria"}})
				in
				  #"Columnas con nombre cambiado"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

