table Dim_Disponibilidad
	lineageTag: 59d8c1f9-c157-4438-b1e9-56efa3b630d8

	column disponibilidad
		dataType: string
		lineageTag: 4b94921a-1d51-47c3-bd89-17fe37f4a839
		summarizeBy: none
		sourceColumn: disponibilidad

		annotation SummarizationSetBy = Automatic

	column id_disponibilidad
		dataType: int64
		formatString: 0
		lineageTag: 5b479b5d-a860-445b-b029-cc435b3f3e13
		summarizeBy: none
		sourceColumn: id_disponibilidad

		annotation SummarizationSetBy = Automatic

	partition Dim_Disponibilidad = m
		mode: import
		source =
				let
				  Origen = Excel.Workbook(File.Contents(RutaMaterial & "nike_data.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Disponibilidad", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"AVAILABILITY", type text}, {"id_AVAILABILITY", Int64.Type}}, "es"),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Tipo de columna cambiado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Filas en blanco eliminadas",{"id_AVAILABILITY", "AVAILABILITY"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"id_AVAILABILITY", "id_disponibilidad"}, {"AVAILABILITY", "disponibilidad"}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado","COMING_SOON","Coming soon",Replacer.ReplaceText,{"disponibilidad"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","IN_STOCK","In stock",Replacer.ReplaceText,{"disponibilidad"}),
				    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","SOLD_OUT","Sold out",Replacer.ReplaceText,{"disponibilidad"})
				in
				  #"Valor reemplazado2"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

