table Dim_Descripcion
	lineageTag: d62808cc-0182-4eb9-adcb-79680d69ecac

	column descripcion
		dataType: string
		lineageTag: 16595a01-c5f2-435a-8249-b8bce0f174ab
		summarizeBy: none
		sourceColumn: descripcion

		annotation SummarizationSetBy = Automatic

	column id_descripcion
		dataType: int64
		formatString: 0
		lineageTag: e59e5925-fae3-45ad-a1b7-da711c9b8d45
		summarizeBy: none
		sourceColumn: id_descripcion

		annotation SummarizationSetBy = Automatic

	partition Dim_Descripcion = m
		mode: import
		source =
				let
				  Origen = Excel.Workbook(File.Contents(RutaMaterial & "nike_data.xlsx"), null, true),
				  #"Navegación 1" = Origen{[Item = "Descripción", Kind = "Sheet"]}[Data],
				  #"Encabezados promovidos" = Table.PromoteHeaders(#"Navegación 1", [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"DESCRIPTION", type text}, {"id_DESCRIPTION", Int64.Type}}, "es"),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Tipo de columna cambiado",{"id_DESCRIPTION", "DESCRIPTION"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"id_DESCRIPTION", "id_descripcion"}, {"DESCRIPTION", "descripcion"}})
				in
				  #"Columnas con nombre cambiado"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

